# Generated by Django 6.0.2 on 2026-02-07 09:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('its_number', models.CharField(help_text='Unique ITS Number', max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(help_text='WhatsApp Number', max_length=20)),
                ('preference', models.CharField(choices=[('AZAAN', 'Azaan'), ('TAKHBIRA', 'Takhbira'), ('BOTH', 'Both')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='auditions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'm4a', 'aac'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audition_files', to='registrations.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duty_type', models.CharField(choices=[('AZAAN', 'Azaan'), ('TAKHBIRA', 'Takhbira')], max_length=10)),
                ('time_label', models.CharField(help_text='e.g. Fajr, Zohr, Maghrib', max_length=50)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='registrations.registration')),
            ],
            options={
                'unique_together': {('date', 'duty_type', 'time_label')},
            },
        ),
    ]
