# Generated by Django 5.2.11 on 2026-02-07 14:42

import django.core.validators
import registrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_alter_auditionfile_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditionfile',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='auditionfile',
            name='audition_display_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='auditionfile',
            name='audition_file_path',
            field=models.FileField(default='', upload_to=registrations.models.audition_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'm4a', 'aac', 'mp4', 'mov', 'webm', 'ogg'])]),
        ),
        migrations.AddField(
            model_name='auditionfile',
            name='audition_file_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=10),
        ),
    ]
