# Generated by Django 5.2.11 on 2026-02-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_remove_auditionfile_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyassignment',
            name='allotment_notification_sent',
            field=models.BooleanField(default=False, help_text='Track allotment WhatsApp notification'),
        ),
        migrations.AddField(
            model_name='registration',
            name='whatsapp_sent',
            field=models.BooleanField(default=False, help_text='Track initial registration WhatsApp'),
        ),
        migrations.AddIndex(
            model_name='dutyassignment',
            index=models.Index(fields=['duty_date'], name='registratio_duty_da_18996b_idx'),
        ),
        migrations.AddIndex(
            model_name='dutyassignment',
            index=models.Index(fields=['namaaz_type'], name='registratio_namaaz__dd1859_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['its_number'], name='registratio_its_num_ac61b4_idx'),
        ),
    ]
