# Generated by Django 5.2.11 on 2026-02-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_dutyassignment_allotment_notification_sent_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['email'], name='registratio_email_2d2215_idx'),
        ),
    ]
