# Generated by Django 5.2.11 on 2026-02-14 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_alter_auditionfile_audition_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhidmatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('cancel', 'Cancel'), ('reallocate', 'Reallocate')], max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, choices=[('FAJAR_AZAAN', 'Fajar Azaan'), ('FAJAR_TAKBIRA', 'Fajar Takbira'), ('ZOHAR_AZAAN', 'Zohar Azaan'), ('ZOHAR_TAKBIRA', 'Zohar Takbira'), ('ASAR_TAKBIRA', 'Asar Takbira'), ('MAGRIB_AZAAN', 'Magrib Azaan'), ('MAGRIB_TAKBIRA', 'Magrib Takbira'), ('ISHAA_TAKBIRA', 'Ishaa Takbira')], max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by_name', models.CharField(blank=True, help_text='Name of the admin who reviewed it', max_length=255, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='registrations.dutyassignment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='registratio_status_6983f3_idx'), models.Index(fields=['assignment'], name='registratio_assignm_2f3923_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('assignment',), name='unique_pending_request_per_assignment')],
            },
        ),
    ]
