# Generated by Django 5.2.11 on 2026-02-14 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0016_khidmatrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=20)),
                ('requested_by_its', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('preferred_datetime', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('duty_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='registrations.dutyassignment')),
            ],
        ),
    ]
