# Generated by Django 5.2.11 on 2026-02-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0018_registration_is_active_alter_registration_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='khidmatrequest',
            name='unique_pending_request_per_assignment',
        ),
        migrations.RemoveIndex(
            model_name='khidmatrequest',
            name='registratio_status_6983f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='khidmatrequest',
            name='registratio_assignm_2f3923_idx',
        ),
        migrations.RemoveIndex(
            model_name='reminder',
            name='registratio_status_273425_idx',
        ),
        migrations.AddField(
            model_name='dutyassignment',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dutyassignment',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dutyassignment',
            name='reallocation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dutyassignment',
            name='reallocation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dutyassignment',
            name='status',
            field=models.CharField(default='allotted', max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='whatsapp_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='whatsapp_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='whatsapp_failed_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='whatsapp_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='whatsapp_status',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='allotment_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='duty_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='khidmatrequest',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='khidmatrequest',
            name='request_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='khidmatrequest',
            name='reviewed_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='khidmatrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(help_text='WhatsApp Number with country code', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='preference',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='registration',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='scheduled_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='channel',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='unlocklog',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='unlocklog',
            name='unlocked_by',
            field=models.CharField(default='Admin', max_length=255),
        ),
    ]
