# Generated by Django 5.2.11 on 2026-02-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0020_fix_database_cascade_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyassignment',
            name='namaaz_type',
            field=models.CharField(choices=[('SANAH', 'Sanah'), ('TAJWEED', 'Tajweed Quran Masjid Tilawat'), ('DUA_E_JOSHAN', 'Dua e Joshan'), ('YASEEN', 'Yaseen'), ('FAJAR_AZAAN', 'Fajar Azaan'), ('FAJAR_TAKBIRA', 'Fajar Takbira'), ('ZOHAR_AZAAN', 'Zohar Azaan'), ('ZOHAR_TAKBIRA', 'Zohar Takbira'), ('ASAR_TAKBIRA', 'Asar Takbira'), ('MAGRIB_AZAAN', 'Magrib Azaan'), ('MAGRIB_TAKBIRA', 'Magrib Takbira'), ('ISHAA_TAKBIRA', 'Ishaa Takbira')], max_length=20),
        ),
    ]
