# Generated by Django 5.2.11 on 2026-02-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0021_reminder_whatsapp_message_id_and_more'),
    ]

    operations = [
    ]
