# Generated by Django 5.2.11 on 2026-02-16 06:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0022_auditionfile_is_selected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Field needing correction (e.g., 'full_name', 'audition_files')", max_length=100)),
                ('admin_message', models.TextField(help_text='Message from admin explaining what to fix')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='registrations.registration')),
            ],
        ),
    ]
