# Generated by Django 5.2.11 on 2026-02-16 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0023_auditionfile_is_selected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyReminderCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('call_status', models.CharField(default='PENDING', max_length=50)),
                ('exotel_call_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duty_assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_reminders', to='registrations.dutyassignment')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.registration')),
            ],
            options={
                'unique_together': {('registration', 'scheduled_time')},
            },
        ),
    ]
