# Generated by Django 5.2.11 on 2026-02-17 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0024_auditionfile_is_selected_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='auditionfile',
        #     name='is_selected',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.AddField(
            model_name='dutyassignment',
            name='removal_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dutyassignment',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dutyassignment',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_duties', to=settings.AUTH_USER_MODEL),
        ),
        # migrations.AddField(
        #     model_name='reminder',
        #     name='whatsapp_message_id',
        #     field=models.CharField(blank=True, max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='reminder',
        #     name='whatsapp_status',
        #     field=models.CharField(default='none', max_length=20),
        # ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_assignments', to='registrations.registration'),
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='namaaz_type',
            field=models.CharField(choices=[('SANAH', 'Sanah'), ('TAJWEED', 'Tajwid Quran Majid Tilawat'), ('DUA_E_JOSHAN', 'Dua e Joshan'), ('YASEEN', 'Yaseen'), ('FAJAR_AZAAN', 'Fajar Azaan'), ('FAJAR_TAKBIRA', 'Fajar Takbira'), ('ZOHAR_AZAAN', 'Zohar Azaan'), ('ZOHAR_TAKBIRA', 'Zohar Takbira'), ('ASAR_TAKBIRA', 'Asar Takbira'), ('MAGRIB_AZAAN', 'Magrib Azaan'), ('MAGRIB_TAKBIRA', 'Magrib Takbira'), ('ISHAA_TAKBIRA', 'Ishaa Takbira')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ALLOTTED', 'Allotted')], default='PENDING', max_length=20),
        ),
    ]
