# Generated by Django 5.2.11 on 2026-02-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0025_auditionfile_is_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditionfile',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='whatsapp_status',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
