# Generated by Django 5.2.11 on 2026-02-19 06:30

import django.core.validators
import registrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0026_auditionfile_is_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditionfile',
            name='audition_file_path',
            field=models.FileField(blank=True, default='', null=True, upload_to=registrations.models.audition_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'm4a', 'aac', 'mp4', 'mov', 'webm', 'ogg'])]),
        ),
    ]
