# Generated by Django 5.2.11 on 2026-02-07 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(help_text='WhatsApp Number with country code (e.g., +919876543210)', max_length=20),
        ),
        migrations.CreateModel(
            name='DutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_date', models.DateField(help_text='Date of the duty')),
                ('namaaz_type', models.CharField(choices=[('FAJAR_AZAAN', 'Fajar Azaan'), ('FAJAR_TAKBIRA', 'Fajar Takbira'), ('ZOHAR_AZAAN', 'Zohar Azaan'), ('ZOHAR_TAKBIRA', 'Zohar Takbira'), ('ASAR_TAKBIRA', 'Asar Takbira'), ('MAGRIB_AZAAN', 'Magrib Azaan'), ('MAGRIB_TAKBIRA', 'Magrib Takbira'), ('ISHAA_TAKBIRA', 'Ishaa Takbira')], max_length=20)),
                ('locked', models.BooleanField(default=True, help_text='Locked duties cannot be changed without unlock')),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_assignments', to='registrations.registration')),
            ],
            options={
                'ordering': ['duty_date', 'namaaz_type'],
                'unique_together': {('duty_date', 'namaaz_type')},
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField(help_text='When to send this reminder')),
                ('email_sent', models.BooleanField(default=False)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('email_attempts', models.IntegerField(default=0)),
                ('whatsapp_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('duty_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='registrations.dutyassignment')),
            ],
            options={
                'ordering': ['scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('success', models.BooleanField()),
                ('message', models.TextField()),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='registrations.reminder')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UnlockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(help_text='Mandatory reason for emergency unlock')),
                ('unlocked_by', models.CharField(default='Admin', help_text='Who performed the unlock', max_length=255)),
                ('duty_date', models.DateField()),
                ('namaaz_type', models.CharField(max_length=20)),
                ('original_user_name', models.CharField(max_length=255)),
                ('original_user_its', models.CharField(max_length=20)),
                ('duty_assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlock_logs', to='registrations.dutyassignment')),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['status', 'scheduled_datetime'], name='registratio_status_273425_idx'),
        ),
    ]
