# Generated by Django 5.2.11 on 2026-02-07 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditionfile',
            name='audio_file',
            field=models.FileField(upload_to='auditions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'm4a', 'aac', 'mp4', 'mov', 'webm', 'ogg'])]),
        ),
    ]
