# Generated by Django 5.2.11 on 2026-02-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_registration_registratio_email_2d2215_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ALLOTTED', 'Allotted')], default='PENDING', max_length=20),
        ),
    ]
