# Generated by Django 5.2.11 on 2026-02-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ALLOTTED', 'Allotted')], db_default='PENDING', default='PENDING', max_length=20),
        ),
    ]
