# Generated by Django 5.2.11 on 2026-02-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_alter_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='whatsapp_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='whatsapp_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, help_text='Meta Message ID (wamid)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='whatsapp_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='whatsapp_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('UNKNOWN', 'Unknown')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='reminder',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='whatsapp_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('UNKNOWN', 'Unknown')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['whatsapp_message_id'], name='registratio_whatsap_a5714f_idx'),
        ),
    ]
