# Generated by Django 5.2.11 on 2026-02-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_update_preference_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='preference',
            field=models.JSONField(default=list),
        ),
    ]
