# Generated by Django 5.2.11 on 2026-02-14 13:39

import django.core.validators
import registrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0014_backfill_dutyassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditionfile',
            name='audition_file_path',
            field=models.FileField(default='', upload_to=registrations.models.audition_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'm4a', 'aac'])]),
        ),
    ]
