# Generated by Django 6.0.2 on 2026-02-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VajebaatAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('its_number', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vajebaat Appointment',
                'verbose_name_plural': 'Vajebaat Appointments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VajebaatForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('its_number', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('mohalla', models.CharField(blank=True, default='', max_length=255)),
                ('file_no', models.CharField(blank=True, default='', max_length=50)),
                ('sector', models.CharField(blank=True, default='', max_length=255)),
                ('sub_sector', models.CharField(blank=True, default='', max_length=255)),
                ('zakat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('khums', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fitra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('kaffara', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('meenat_binyan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('najwa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vajebaat Form',
                'verbose_name_plural': 'Vajebaat Forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VajebaatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('its_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('mohalla', models.CharField(blank=True, default='', max_length=255)),
                ('file_no', models.CharField(blank=True, default='', max_length=50)),
                ('sector_incharge', models.CharField(blank=True, default='', max_length=255)),
                ('subsector_incharge', models.CharField(blank=True, default='', max_length=255)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vajebaat Member',
                'verbose_name_plural': 'Vajebaat Members',
                'ordering': ['-created_at'],
            },
        ),
    ]
