# Generated by Django 6.0.2 on 2026-03-03 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vajebaat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VajebaatDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vajebaat Date',
                'verbose_name_plural': 'Vajebaat Dates',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='vajebaatappointment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VajebaatSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='vajebaat.vajebaatdate')),
            ],
            options={
                'verbose_name': 'Vajebaat Slot',
                'verbose_name_plural': 'Vajebaat Slots',
                'ordering': ['date', 'slot_number'],
                'unique_together': {('date', 'slot_number')},
            },
        ),
        migrations.AddField(
            model_name='vajebaatappointment',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='vajebaat.vajebaatslot'),
        ),
    ]
