# Generated by Django 6.0.2 on 2026-03-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vajebaat', '0002_vajebaatdate_vajebaatappointment_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vajebaatmember',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
