# Generated by Django 5.2.11 on 2026-03-05 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vajebaat', '0003_add_email_to_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='vajebaatappointment',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='vajebaatappointment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='vajebaat.vajebaatmember'),
        ),
    ]
