# Generated by Django 5.2.11 on 2026-03-07 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vajebaat', '0006_alter_vajebaatappointment_preferred_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('its_id', models.BigIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_sector', models.CharField(blank=True, max_length=255, null=True)),
                ('file_no', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Legacy Member',
                'verbose_name_plural': 'Legacy Members',
                'db_table': 'members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VajebaatRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('its_id', models.BigIntegerField()),
                ('year', models.IntegerField(default=1447)),
                ('zakat_mal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('khums', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nazr_muqam', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kaffara', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minnat_niyaz', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('najwa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('jamiya', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vajebaat_records', to='vajebaat.vajebaatappointment')),
            ],
            options={
                'verbose_name': 'Vajebaat Record',
                'verbose_name_plural': 'Vajebaat Records',
                'db_table': 'vajebaat_records',
            },
        ),
    ]
