# Generated by Django 5.2.11 on 2026-03-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vajebaat', '0007_legacymember_vajebaatrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vajebaatrecord',
            name='its_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
